apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  namespace: submission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: consumer-service:0.0.3
          envFrom:
            - configMapRef:
                name: submission-config
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          env:
            - name: RESULTS_TOPIC
              value: "code-results"
