apiVersion: v1
kind: Namespace
metadata:
  name: "kafka"
  labels:
    name: "kafka"
---
apiVersion: v1
kind: Namespace
metadata:
  name: "submission-service"
  labels:
    name: "submission-service"
