apiVersion: v1
kind: ConfigMap
metadata:
  name: submission-config
  namespace: submission-service
data:
  KAFKA_BROKERS: "kafka.kafka.svc.cluster.local:9092"
  SUBMISSION_TOPIC: "code-submissions"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-service
  namespace: submission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submission-service
  template:
    metadata:
      labels:
        app: submission-service
    spec:
      containers:
      - name: submission-service
        image: submission-service:0.0.1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: submission-config
---
apiVersion: v1
kind: Service
metadata:
  name: submission-service
  namespace: submission-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: submission-service
